---
### Common variables
# Default mode for running the playbook
# Possible values:
#  - install
#  - enroll
#  - unenroll
#  - remove
run_option: install

# Repository configuration file to use on RedHat OS
# Default value:
#   redhat_repo: /etc/yum.repos.d/centrify.repo
redhat_repo: /etc/yum.repos.d/centrify.repo

# Repository configuration file and line to use on Debian OS
# Your Repo Credentials can be found from the Centrify Download Center after creation of a Repo Key.
# You may also edit the information of the debian_repo_config to point to an internal mirror in case systems targeted by Ansible may not have Internet access.
# Default values:
#   debian_repo: /etc/apt/sources.list
#   debian_repo_config: deb https://<REPOKEY>@repo.centrify.com/deb stable main
debian_repo: /etc/apt/sources.list
debian_repo_config: 

# Repository configuration file to use on SuSE OS
# Default value:
#   suse_repo: /etc/zypp/repos.d/centrify-rpm-suse.repo
suse_repo: /etc/zypp/repos.d/centrify-rpm-suse.repo

### Centrify Privileged Access Services variables
# Centrify PAS Platform tenant URL to use
# Example:
#   tenant_url: https://company.my.centrify.net
tenant_url: 

# URL to use to download the Centrify Client for Windows from PAS Platform.
# This URL can be found on the Download section of the Centrify PAS Portal.
# Default:
#   cagent_url: http://edge.centrify.com/products/cloud-service/WindowsAgent/Centrify/cagentinstaller.msi
cagent_url: http://edge.centrify.com/products/cloud-service/WindowsAgent/Centrify/cagentinstaller.msi

# Registration code to use for Centrify Client enrolment to the Centrify PAS Platform.
# This code must be generated by a System Administrator under section Settings > Enrollment > Enrollment Codes of the Centrify PAS Portal.
# Example: 
#   registration_code: 3JWTTQ3TZWM3AGEODG3LDVMXUYUGKADNU2IW13VXC8W1
registration_code: 