---
## Common variables
# Task to execute running the playbook
# Possible values:
#  - install
#  - enroll
#  - unenroll
#  - remove
centrify_auth_task: enroll

# URL Token for Centrify repo
# No default value, you must use the URL Token value you generated on Centrify Download Center
# More details here: https://www.centrify.com/support/customer-support-portal/repo
# Note that this variable is shared by all Centrify Roles where it is used as there is need for a single URL token per repository
centrify_redhat_urltoken:
centrify_debian_urltoken:
centrify_suse_urltoken:

### Centrify Authentication and Privilege Elevation Services variables
# Active Directory domain name to use during join operations
# Example:
#   centrify_auth_domain: aasgaard.lab
centrify_auth_domain: 

# Active Directory Service Account to use during join operations
# Example:
#   centrify_auth_service_principal: svc_centrifyadjoin@AASGAARD.LAB
centrify_auth_service_principal: 

# Location of the Kerberos Keytab file to use during join operations
# Default:
#   centrify_auth_service_keytab: /etc/adjoin.keytab
centrify_auth_service_keytab: /etc/adjoin.keytab

# Location of the Kerberos Realm configuration file to use during join operations
# Default:
#   centrify_auth_realm_config: /etc/krb5.conf
centrify_auth_realm_config: /etc/krb5.conf

# Active Directory container to use for Computers object during join operations
# Example:
#   centrify_auth_container: aasgaard.lab/Centrify/Computers
centrify_auth_container: 

# Centrify Zone to use during join operations
# Example:
#   centrify_auth_zone: aasgaard.lab/Centrify/Zones/Global/Linux
centrify_auth_zone: 
