---
## Common variables
# Default mode for running the playbook
# Possible values:
#  - install
#  - enroll
#  - unenroll
#  - remove
centrify_auth_run_option: enroll

# Repository configuration file to use on RedHat OS
# Default value:
#   centrify_auth_redhat_repo: /etc/yum.repos.d/centrify.repo
centrify_auth_redhat_repo: /etc/yum.repos.d/centrify.repo

# Repository configuration file and line to use on Debian OS
# Your Repo Credentials can be found from the Centrify Download Center after creation of a Repo Key.
# You may also edit the information of the debian_repo_config to point to an internal mirror in case systems targeted by Ansible may not have Internet access.
# Default values:
#   centrify_auth_debian_repo: /etc/apt/sources.list.d/centrify.list
centrify_auth_debian_repo: /etc/apt/sources.list.d/centrify.list

# Repository configuration file to use on SuSE OS
# Default value:
#   centrify_auth_suse_repo: /etc/zypp/repos.d/centrify-rpm-suse.repo
centrify_auth_suse_repo: /etc/zypp/repos.d/centrify-rpm-suse.repo

### Centrify Authentication and Privilege Elevation Services variables
# Active Directory domain name to use during join operations
# Example:
#   centrify_auth_domain: aasgaard.lab
centrify_auth_domain: 

# Active Directory Service Account to use during join operations
# Example:
#   centrify_auth_service_principal: svc_centrifyadjoin@AASGAARD.LAB
centrify_auth_service_principal: 

# Location of the Kerberos Keytab file to use during join operations
# Default:
#   centrify_auth_service_keytab: /etc/adjoin.keytab
centrify_auth_service_keytab: /etc/adjoin.keytab

# Location of the Kerberos Realm configuration file to use during join operations
# Default:
#   centrify_auth_realm_config: /etc/krb5.conf
centrify_auth_realm_config: /etc/krb5.conf

# Active Directory container to use for Computers object during join operations
# Example:
#   centrify_auth_container: aasgaard.lab/Centrify/Computers
centrify_auth_container: 

# Centrify Zone to use during join operations
# Example:
#   centrify_auth_zone: aasgaard.lab/Centrify/Zones/Global/Linux
centrify_auth_zone: 
