# Install Centrify Client package
- name: Linux OS family
  block:
  
    - name: Check if CentrifyCC is installed
      package_facts:

    - name: Install CentrifyCC package 
      include_tasks: "install-{{ ansible_os_family|lower }}.yml"
      when: '"centrifycc" not in ansible_facts.packages|lower'
  
  when: ansible_os_family in ["Debian", "RedHat", "Suse"]
  
- name: Windows OS family
  block:
  
    - name: Check if CAgent is installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{43A16456-62CD-45A2-B2DF-743BA7A56894}
      register: cagent_installed
      
    - name: Install CAgent package
      include_tasks: "install-windows.yml"
      when: cagent_installed.exists == false
      
  when: ansible_os_family == "Windows"