# Remove Centrify Client package
- name: Remove CentrifyCC package
  yum:
    name: CentrifyCC
    state: absent

- name: Delete Centrify Repo
  file:
    path: /etc/yum.repos.d/centrify.repo 
    state: absent
