# Remove Centrify Client package
- name: Check if CentrifyCC is installed
  zypper:
    name: CentrifyCC
  register: zyp_cmd

- name: Remove Centrify Client package
  block:

    - name: Check if computer is joined to PAS Platform
      command: cinfo
      register: cinfo_cmd
      changed_when: cinfo_cmd.rc == 0
      failed_when:
        - cinfo_cmd.rc != 10
        - cinfo_cmd.rc != 0

    - name: Unenroll from PAS Platform before removal
      include_tasks: Suse-unenroll.yml
      when: cinfo_cmd.rc == 0

    - name: Remove CentrifyCC package
      zypper:
        name: CentrifyCC
        state: absent

    - name: Delete centrify-rpm-suse.repo
      file:
        path: "{{ centrify_vault_suse_repo }}"
        state: absent

  when: zyp_cmd.results | selectattr("zypstate", "match", "installed") | list | length == 1
