# Install Centrify Client package
- name: Check if CentrifyCC is installed
  zypper:
    list: 'CentrifyCC'
  register: zyp_cmd
  changed_when: zyp_cmd.results | selectattr("zypstate", "match", "installed") | list | length == 0

- name: Install on Suse family using Zypper
  block:

    - name: Check if centrify-rpm-suse.repo exists
      stat:
        path: "{{ centrify_vault_suse_repo }}"
      register: filecheck

    - name: Create centrify-rpm-suse.repo if it doesn't exist
      copy:
        src: suse.repo
        dest: "{{ centrify_vault_suse_repo }}"
        owner: root
        group: root
        mode: '0644'
      when: filecheck.stat.exists == false

    - name: Install Centrify Client package
      zypper:
        update_cache: yes
        name: CentrifyCC
        state: latest

  when: zyp_cmd.results | selectattr("zypstate", "match", "installed") | list | length == 0
