# Enroll computer to Centrify PAS Platform
- name: Check if CentrifyCC is installed
  zypper:
    name: 'CentrifyCC'
  register: zyp_cmd

- name: Install CentrifyCC before joining to PAS Platform
  include_tasks: Suse-install.yml
  when: zyp_cmd.results | selectattr("zypstate", "match", "installed") | list | length == 0

- name: Check if computer is enrolled to Centrify Identity Platform
  command: cinfo
  register: cinfo_cmd
  changed_when: cinfo_cmd.rc == 10
  failed_when:
    - cinfo_cmd.rc != 10
    - cinfo_cmd.rc != 0

- name: Enroll system to PAS Platform
  block:

    - name: Enroll system using registration code
      command: cenroll --tenant "{{ centrify_vault_tenant_url }}" --code "{{ centrify_vault_registration_code }}" --features "{{ centrify_vault_features }}" --force --verbose

    - name: Post Enrolment tasks
      include_tasks: post-enroll.yml

  when: cinfo_cmd.rc == 10
