# Unenroll computer from Centrify Identity Platform
- name: Unenroll Linux system from Centrify Identity Platform
  block:

    - name: Check if CentrifyCC is installed
      yum:
        list: 'CentrifyCC'
      register: yum_cmd

    - name: Check if computer is enrolled to Centrify Identity Platform
      command: cinfo
      register: cinfo_cmd
      changed_when: cinfo_cmd.rc == 0
      failed_when:
        - cinfo_cmd.rc != 10
        - cinfo_cmd.rc != 0

    - name: Unenroll computer from Centrify Identity Platform
      block:

        - name: Unenroll the computer from Centrify tenant without deleting System
          command: cunenroll --machine --verbose

      when:
        - yum_cmd.results | selectattr("yumstate", "match", "installed") | list | length == 1
        - cinfo_cmd.rc == 0

  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian" or ansible_os_family == "Suse"

- name: Unenroll Windows system from Centrify Identity Platform
  block:

    - name: Check if CAgent is installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FE8C7229-27DC-4646-86C6-78EE95B9C33E}
      register: cagent_installed

    - name: Check if computer is enrolled to Centrify Identity Platform
      win_command: cinfo.exe
      args:
        chdir: C:\Program Files\Centrify\cagent\
      register: cinfo_cmd
      changed_when: cinfo_cmd.rc == 0
      failed_when:
        - cinfo_cmd.rc != 10
        - cinfo_cmd.rc != 0
      when: cagent_installed.exists == true

    - name: Enroll computer to Centrify Identity Platform
      block:

        - name: Unenroll the computer from Centrify tenant without deleting System
          win_command: cunenroll.exe --machine --verbose
          args:
            chdir: C:\Program Files\Centrify\cagent\

      when:
        - cagent_installed.exists == true
        - cinfo_cmd.rc == 0

  when: ansible_os_family == "Windows"
