# Remove Centrify Client package
- name: Check if CAgent is installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{43A16456-62CD-45A2-B2DF-743BA7A56894}
  register: cagent_installed

- name: Remove Centrify Client package
  block:

    - name: Check if system is enrolled to PAS Platform
      win_command: cinfo.exe
      args:
        chdir: C:\Program Files\Centrify\cagent\
      register: cinfo_cmd
      changed_when: cinfo_cmd.rc == 0
      failed_when:
        - cinfo_cmd.rc != 10
        - cinfo_cmd.rc != 0

    - name: Unenroll before removing Centrify Client package
      include_tasks: Windows-unenroll.yml
      when: cinfo_cmd.rc == 0

    - name: Uninstall Centrify Client package 
      win_command: msiexec.exe /x {43A16456-62CD-45A2-B2DF-743BA7A56894} /qn /norestart
      args:
        chdir: C:\Windows\System32\

  when: cagent_installed.exists == true
