# Enroll computer to Centrify Identity Platform
- name: Check if CAgent is installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{43A16456-62CD-45A2-B2DF-743BA7A56894}
  register: cagent_installed

- name: Install CAgent before enrolling to PAS Platform
  include_tasks: Windows-install.yml
  when: cagent_installed.exists == false

- name: Check if system is enrolled to PAS Platform
  win_command: cinfo.exe
  args:
    chdir: C:\Program Files\Centrify\cagent\
  register: cinfo_cmd
  changed_when: cinfo_cmd.rc == 10
  failed_when:
    - cinfo_cmd.rc != 10
    - cinfo_cmd.rc != 0

- name: Enroll system to PAS Platform
  block:

    - name: Enroll system using registration code
      win_command: cenroll.exe --tenant "{{ centrify_vault_tenant_url }}" --code "{{ centrify_vault_registration_code }}" --features "{{ centrify_vault_features }}" --force --verbose
      args:
        chdir: C:\Program Files\Centrify\cagent\

  when: cinfo_cmd.rc == 10
