# Install on Suse family using Zypper
- name: Check if Centrify repo exists
  stat:
    path: /etc/zypp/repos.d/centrify-rpm-suse.repo 
  register: filecheck

- name: Create Centrify repo if it doesn't exist
  shell: curl -1sLf 'https://cloudrepo.centrify.com/{{ centrify_suse_urltoken }}/rpm-suse/cfg/setup/bash.rpm.sh' | sudo -E bash
  args:
    warn: false
  when: filecheck.stat.exists == false

- name: Install Centrify Audit Agent package
  zypper:
    name: CentrifyDA
    state: latest
