# Remove Centrify Audit Agent package
- name: Remove CentrifyDA package
  apt:
    name: centrifyda
    state: absent

- name: Delete Centrify Repo
  file:
    path: /etc/apt/sources.list.d/centrify-deb.list
    state: absent
