# Remove Centrify Audit Agent package
- name: Remove CentrifyDA package
  zypper:
    name: CentrifyDA
    state: absent

- name: Delete Centrify Repo
  file:
    path: /etc/zypp/repos.d/centrify-rpm-suse.repo 
    state: absent
