# Enroll computer to Active Directory
- name: Check if CentrifyDC is installed
  yum:
    list: 'CentrifyDC'
  register: apt_cmd

- name: Install CentrifyDC before joining AD domain
  include_tasks: RedHat-install.yml
  when: apt_cmd.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: Check if computer is joined to domain
  command: adinfo
  register: adinfo_cmd
  changed_when: adinfo_cmd.rc == 10
  failed_when:
    - adinfo_cmd.rc != 10
    - adinfo_cmd.rc != 0

- name: Enroll computer to Active Directory
  block:

    - name: Copy kerberos config file to guarantee finding realm
      copy:
        src: krb5.conf
        dest: "{{ centrify_auth_realm_config }}"
        owner: root
        group: root
        mode: '0644'

    - name: Copy service account's keytab file
      copy:
        src: adjoin.keytab
        dest: "{{ centrify_auth_service_keytab }}"
        owner: root
        group: root
        mode: '0600'

    - name: Join the computer to Active Directory domain using kerberos
      shell: |
        kinit -kt "{{ centrify_auth_service_keytab }}" "{{ centrify_auth_service_principal }}"
        adjoin "{{ centrify_auth_domain }}" --container "{{ centrify_auth_container }}" --zone "{{ centrify_auth_zone }}" --verbose
        kdestroy
        shred --iterations=1 --remove "{{ centrify_auth_service_keytab }}"

  when: adinfo_cmd.rc == 10
