# Remove Centrify Agent package
- name: Check if CentrifyDC is installed
  apt:
    list: CentrifyCC
  register: apt_cmd

- name: Remove Centrify Agent package
  block:

    - name: Check if computer is joined to Active Directory
      command: cinfo
      register: cinfo_cmd
      changed_when: cinfo_cmd.rc == 0
      failed_when:
        - cinfo_cmd.rc != 10
        - cinfo_cmd.rc != 0

    - name: Unenroll from Active Directory before removal
      include_tasks: Debian-unenroll.yml
      when: cinfo_cmd.rc == 0

    - name: Remove CentrifyDC, CentrifyDC-curl, CentrifyDC-openldap, CentrifyDC-openssl (and CentrifyDA if installed)
      yum:
        name: CentrifyD*
        state: absent

    - name: Delete centrify.list
      file:
        path: "{{ centrify_auth_debian_repo }}"
        state: absent

  when: apt_cmd.results | selectattr("aptstate", "match", "installed") | list | length == 1
