# Install Centrify Agent package
- name: Check if CentrifyDC is installed
  apt:
    list: 'CentrifyDC'
  register: apt_cmd
  changed_when: apt_cmd.results | selectattr("aptstate", "match", "installed") | list | length == 0

- name: Install on Debian family using Aptitude
  block:

    - name: Check if centrify.list exists
      stat:
        path: "{{centrify_auth_debian_repo}}"
      register: filecheck

    - name: Create centrify.list if it doesn't exist
      copy:
        src: debian.repo
        dest: "{{ centrify_auth_debian_repo }}"
        owner: root
        group: root
        mode: '0644'
      when: filecheck.stat.exists == false

    - name: Install Centrify Agent packages
      apt:
        update_cache: yes
        name: CentrifyDC
        state: latest

  when: apt_cmd.results | selectattr("aptstate", "match", "installed") | list | length == 0
