# Enroll computer to Active Directory
- name: Enroll Linux system to Active Directory and Centrify Zone
  block:
  
    - name: Check if CentrifyDC is installed
      yum:
        list: 'CentrifyDC'
      register: yum_cmd

    - name: Check if computer is joined to domain
      command: adinfo
      register: adinfo_cmd
      changed_when: adinfo_cmd.rc == 10
      failed_when:
        - adinfo_cmd.rc != 10
        - adinfo_cmd.rc != 0

    - name: Enroll computer to Active Directory
      block:

        - name: Copy kerberos config file to guarantee finding realm
          copy:
            src: krb5.conf 
            dest: "{{realm_config}}"
            owner: root
            group: root
            mode: '0644'

        - name: Copy service account's keytab file
          copy:
            src: adjoin.keytab 
            dest: "{{service_keytab}}"
            owner: root
            group: root
            mode: '0600'

        - name: Join the computer to Active Directory domain using kerberos
          shell: |
            kinit -kt "{{service_keytab}}" "{{service_principal}}"
            adjoin "{{domain_name}}" --container "{{computer_container}}" --zone "{{centrify_zone}}" --verbose
            kdestroy
            shred --iterations=1 --remove "{{service_keytab}}"

      when:
        - yum_cmd.results | selectattr("yumstate", "match", "installed") | list | length == 1
        - adinfo_cmd.rc == 10
    
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian" or ansible_os_family == "Suse"

- name:  Enroll Windows system to Centrify Zone
  block:

    - name: Check if Centrify Agent is installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FE1863FD-8090-4547-94AD-472A0DC42988}
      register: cagent_installed

    - name: Check if computer is joined to Centrify Zone
      win_command: dzinfo.exe
      args:
        chdir: 'C:\Program Files\Centrify\Centrify Agent for Windows\'
      register: dzinfo_cmd
      changed_when: dzinfo_cmd.rc == 1
      failed_when:
        - dzinfo_cmd.rc != 1
        - dzinfo_cmd.rc != 0

    - name: Enroll computer to Centrify Zone
      block:

        - name: Copy PowerShell script for Centrify Zone enrolment 
          win_copy:
            src: Join-CentrifyZone.ps1 
            dest: C:\Windows\Temp\Join-CentrifyZone.ps1

        - name: Join the computer to Centrify Zone using prepared Windows Computer 
          win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\Join-CentrifyZone.ps1

      when:
        - cagent_installed.exists == true
        - dzinfo_cmd.rc == 1

  when: ansible_os_family == "Windows"
