# Install Centrify Authentication Agents
- name: Install on Redhat family using Yum
  block:

    - name: Check if centrify.repo exists
      stat:
        path: "{{redhat_repo}}"
      register: filecheck

    - name: Create centrify.repo if it doesn't exist
      copy:
        src: redhat.repo 
        dest: "{{redhat_repo}}"
        owner: root
        group: root
        mode: '0644'
      when: filecheck.stat.exists == false

    - name: Install Centrify Authentication Agent packages
      yum:
        update_cache: yes
        name: CentrifyDC
        state: latest

  when: ansible_os_family == "RedHat"

- name: Install on Debian family using Aptitude
  block:

    - name: Ensure that centrify repo exists in sources.list
      lineinfile:
        path: "{{debian_repo}}"
        line: "{{debian_repo_config}}"
        state: present

    - name: Install Centrify Authentication Agent package
      apt:
        update_cache: yes
        name: CentrifyDC
        state: latest

  when: ansible_os_family == "Debian"

- name: Install on Suse family using Zypper
  block:

    - name: Check if centrify-rpm-suse.repo exists
      stat:
        path: "{{suse_repo}}"
      register: filecheck

    - name: Create centrify-rpm-suse.repo if it doesn't exist
      copy:
        src: suse.repo 
        dest: "{{suse_repo}}"
        owner: root
        group: root
        mode: '0644'
      when: filecheck.stat.exists == false

    - name: Install Centrify Authentication Agent package
      zypper:
        update_cache: yes
        name: CentrifyDC
        state: latest

  when: ansible_os_family == "Suse"

- name: Install on Windows using MS Installer
  block:

    - name: Check if Centrify Authentication Agent is installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FE1863FD-8090-4547-94AD-472A0DC42988}
      register: cagent_installed

    - name: Install Centrify Client
      block:

        - name: Copy package to temp directory
          win_copy:
            src: "Centrify Agent for Windows64.msi"
            dest: C:\Windows\Temp\CentrifyAgentforWindows64.msi

        - name: Install Centrify Client package
          win_command: msiexec.exe /i C:\Windows\Temp\CentrifyAgentforWindows64.msi /qn /norestart
          args:
            chdir: C:\Windows\System32\
          register: msiexec_cmd
          failed_when:
            - msiexec_cmd.rc != 3010
            - msiexec_cmd.rc != 0

        - name: Reboot Windows system after Agent installation
          win_reboot:

      when: cagent_installed.exists == false

  when: ansible_os_family == "Windows"  
