# Remove computer from Active Directory
- name: Check if computer is joined to domain
  command: adinfo
  register: adinfo_cmd
  changed_when: adinfo_cmd.rc == 0
  failed_when:
    - adinfo_cmd.rc != 10
    - adinfo_cmd.rc != 2
    - adinfo_cmd.rc != 0

- name: Remove computer from  Active Directory
  block:

    - name: Copy service account's keytab file
      copy:
        src: adjoin.keytab
        dest: "{{ centrify_auth_service_keytab }}"
        owner: root
        group: root
        mode: '0600'

    - name: Leave Active Directory domain using Kerberos
      shell: |
        kinit -kt "{{ centrify_auth_service_keytab }}" "{{ centrify_auth_service_principal }}"
        adleave --remove --verbose
        kdestroy
        shred --iterations=1 --remove "{{ centrify_auth_service_keytab }}"

  when: adinfo_cmd.rc == 0
