# Uninstall Centrify Authentication Agent
- name: Check if CentrifyDC is installed
  yum:
    list: CentrifyDC
  register: yum_cmd

- name: Remove Centrify Agent packages
  block:

    - name: Check if computer is joined to Active Directory
      command: adinfo
      register: adinfo_cmd
      changed_when: adinfo_cmd.rc == 0
      failed_when:
        - adinfo_cmd.rc != 10
        - adinfo_cmd.rc != 0

    - name: Unenroll from AD domain before removing CentrifyDC
      include_tasks: RedHat-unenroll.yml
      when: adinfo_cmd.rc == 0

    - name: Remove CentrifyDC, CentrifyDC-curl, CentrifyDC-openldap, CentrifyDC-openssl (and CentrifyDA if installed)
      yum:
        name: CentrifyD*
        state: absent

    - name: Delete centrify.repo
      file:
        path: "{{ centrify_auth_redhat_repo }}"
        state: absent

  when: yum_cmd.results | selectattr("yumstate", "match", "installed") | list | length == 1
