# Uninstall Centrify Authentication Agent
- name: Remove Centrify Agent from RedHat system
  block:

    - name: Check if CentrifyDC is installed
      yum:
        list: CentrifyDC
      register: yum_cmd

    - name: Check if computer is joined to Active Directory
      command: adinfo
      register: adinfo_cmd
      changed_when: adinfo_cmd.rc == 10
      failed_when:
        - adinfo_cmd.rc != 10
        - adinfo_cmd.rc != 0

    - name: Remove Centrify Agent packages
      block:

        - name: Remove CentrifyDC, CentrifyDC-curl, CentrifyDC-openldap, CentrifyDC-openssl (and CentrifyDA if installed)
          yum:
            name: CentrifyDC
            state: absent

        - name: Delete centrify.repo
          file:
            path: "{{redhat_repo}}"
            state: absent

      when:
        - yum_cmd.results | selectattr("yumstate", "match", "installed") | list | length == 1
        - adinfo_cmd.rc == 10

  when: ansible_os_family == "RedHat"

- name: Remove Centrify Agent from Debian system
  block:

    - name: Check if CentrifyDC is installed
      apt:
        list: CentrifyCC
      register: apt_cmd

    - name: Check if computer is joined to Active Directory
      command: adinfo
      register: adinfo_cmd
      changed_when: adinfo_cmd.rc == 10
      failed_when:
        - adinfo_cmd.rc != 10
        - adinfo_cmd.rc != 0

    - name: Remove Centrify Agent package
      block:

        - name: Remove CentrifyDC, CentrifyDC-curl, CentrifyDC-openldap, CentrifyDC-openssl (and CentrifyDA if installed)
          yum:
            name: CentrifyDC
            state: absent

        - name: Delete Centrify entry from sources.list 
          lineinfile:
            path: "{{debian_repo}}"
            line: "{{debian_repo_config}}"
            state: absent

      when:
        - apt_cmd.results | selectattr("aptstate", "match", "installed") | list | length == 1
        - adinfo_cmd.rc == 10

  when: ansible_os_family == "Debian"

- name: Remove Centrify Client from SuSE system
  block:

    - name: Check if CentrifyDC is installed
      zypper:
        list: CentrifyDC
      register: zypper_cmd

    - name: Check if computer is joined to Active Directory
      command: adinfo
      register: adinfo_cmd
      changed_when: adinfo_cmd.rc == 10
      failed_when:
        - adinfo_cmd.rc != 10
        - adinfo_cmd.rc != 0

    - name: Remove Centrify Agent packages
      block:

        - name: Remove CentrifyDC, CentrifyDC-curl, CentrifyDC-openldap, CentrifyDC-openssl (and CentrifyDA if installed)
          yum:
            name: CentrifyDC
            state: absent

        - name: Delete centrify-rpm-suse.repo
          file:
            path: "{{suse_repo}}"
            state: absent

      when:
        - zypper_cmd.results | selectattr("zypperstate", "match", "installed") | list | length == 1
        - adinfo_cmd.rc == 10

  when: ansible_os_family == "Suse"

- name: Remove Centrify Agent from Windows system
  block:

    - name: Check if Centrify Agent is installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FE1863FD-8090-4547-94AD-472A0DC42988}
      register: cagent_installed

    - name: Check if computer is joined to Centrify Zone
      win_command: dzinfo.exe
      args:
        chdir: 'C:\Program Files\Centrify\Centrify Agent for Windows\'
      register: dzinfo_cmd
      changed_when: dzinfo_cmd.rc == 1
      failed_when:
        - dzinfo_cmd.rc != 1
        - dzinfo_cmd.rc != 0

    - name: Remove Centrify Agent package
      block:

        - name: Uninstall Centrify Agent package 
          win_command: msiexec.exe /x {FE1863FD-8090-4547-94AD-472A0DC42988} /qn
          args:
            chdir: C:\Windows\System32\
          register: msiexec_cmd
          failed_when:
            - msiexec_cmd.rc != 1641
            - msiexec_cmd.rc != 0

      when:
        - cagent_installed.exists == true
        - dzinfo_cmd.rc == 1

  when: ansible_os_family == "Windows"
