# Unenroll computer from Centrify Zone
- name: Linux OS family
  block:
  
    - name: Check if computer is enrolled to Centrify Zone
      command: adinfo
      register: adinfo_cmd
      changed_when: adinfo_cmd.rc == 0
      failed_when:
        - adinfo_cmd.rc != 10
        - adinfo_cmd.rc != 2
        - adinfo_cmd.rc != 0

    - name: Remove computer from Centrify Zone
      block:

        - name: Copy service account's keytab file
          copy:
            src: adjoin.keytab
            dest: "{{ centrify_auth_service_keytab }}"
            owner: root
            group: root
            mode: '0600'

        - name: Leave Active Directory domain using Kerberos
          shell: |
            kinit -kt "{{ centrify_auth_service_keytab }}" "{{ centrify_auth_service_principal }}"
            adleave --remove --verbose
            kdestroy
            shred --iterations=1 --remove "{{ centrify_auth_service_keytab }}"
      when: adinfo_cmd.rc == 0

  when: ansible_os_family in ["Debian", "RedHat", "Suse"]
  
- name: Windows OS family
block:

    - name: Check if computer is enrolled to Centrify Zone
      win_command: dzinfo.exe
      args:
        chdir: 'C:\Program Files\Centrify\Centrify Agent for Windows\'
      register: dzinfo_cmd
      changed_when: dzinfo_cmd.rc == 0
      failed_when:
        - dzinfo_cmd.rc != 1
        - dzinfo_cmd.rc != 2
        - dzinfo_cmd.rc != 0

    - name: Remove computer from Centrify Zone
      block:

        - name: Unenroll the computer from Centrify Zone without restart
          win_shell: dzleave.exe /r no /f
          ignore_errors: yes
          args:
            chdir: 'C:\Program Files\Centrify\Centrify Agent for Windows\'
          when: dzinfo_cmd.rc == 0
  
when: ansible_os_family == "Windows"