# Install Centrify Authentication Agents
- name: Check if Centrify Authentication Agent is installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FE1863FD-8090-4547-94AD-472A0DC42988}
  register: cagent_installed

- name: Install Centrify Client
  block:

    - name: Copy package to temp directory
      win_copy:
        src: "Centrify Agent for Windows64.msi"
        dest: C:\Windows\Temp\CentrifyAgentforWindows64.msi

    - name: Install Centrify Client package
      win_command: msiexec.exe /i C:\Windows\Temp\CentrifyAgentforWindows64.msi /qn /norestart
      args:
        chdir: C:\Windows\System32\
      register: msiexec_cmd
      failed_when:
        - msiexec_cmd.rc != 3010
        - msiexec_cmd.rc != 0

    - name: Reboot Windows system after Agent installation
      win_reboot:

  when: cagent_installed.exists == false
