# Enroll computer to Active Directory
- name: Check if Centrify Agent is installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FE1863FD-8090-4547-94AD-472A0DC42988}
  register: cagent_installed

- name: Install Centrify Agent before joining AD domain
  include_tasks: Windows-install.yml
  when: cagent_installed.exists == false

- name: Check if computer is joined to Centrify Zone
  win_command: dzinfo.exe
  args:
    chdir: 'C:\Program Files\Centrify\Centrify Agent for Windows\'
  register: dzinfo_cmd
  changed_when: dzinfo_cmd.rc == 1
  failed_when:
    - dzinfo_cmd.rc != 1
    - dzinfo_cmd.rc != 0

- name: Enroll computer to Centrify Zone
  block:

    - name: Copy PowerShell script for Centrify Zone enrolment
      win_copy:
        src: Join-CentrifyZone.ps1
        dest: C:\Windows\Temp\Join-CentrifyZone.ps1

    - name: Join the computer to Centrify Zone using prepared Windows Computer
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Windows\Temp\Join-CentrifyZone.ps1

  when: dzinfo_cmd.rc == 1
