# Remove computer from Active Directory
- name: Check if Centrify Agent is installed
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{FE1863FD-8090-4547-94AD-472A0DC42988}
  register: cagent_installed

- name: Check if computer is enrolled to Centrify Identity Platform
  win_command: dzinfo.exe
  args:
    chdir: 'C:\Program Files\Centrify\Centrify Agent for Windows\'
  register: dzinfo_cmd
  changed_when: dzinfo_cmd.rc == 0
  failed_when:
    - dzinfo_cmd.rc != 1
    - dzinfo_cmd.rc != 0

- name: Remove computer from Centrify Zone
  block:

    - name: Unenroll the computer from Centrify Zone without restart
      win_shell: dzleave.exe /r no /f
      ignore_errors: yes
      args:
        chdir: 'C:\Program Files\Centrify\Centrify Agent for Windows\'

  when:
    - cagent_installed.exists == true
    - dzinfo_cmd.rc == 0
